### ISSUE TITLE
Straight conversion of string to constant doesn't work in all cases

### ISSUE THREAD

**Issue by b-morgan** [SpareSimian/FixPlaySound#1]
There are some strings that don't convert straight into an upper case constant. "UChatScrollButton" is one example.

**Comment by b-morgan** [comment]
"UChatScrollButton" is a bad example but I'm pretty sure I've manually changed others that didn't have a constant. Probably should ignore this for now until I find or remember another example.

**Comment by SpareSimian** [comment]
I've special-cased a few where adding an underscore before every capital letter doesn't work. See the end of the function camelCaseToUpperCase for those.
