### ISSUE TITLE
Misses a rare usage or two

### ISSUE THREAD

**Issue by Hentaya** [SpareSimian/FixPlaySound#2]
Thanks for the great work, just ran it, found two stragglers:

 		self:PlaySound("adds", "Info") 
and
 		PlaySound("ReadyCheck", "master") 

Were the only two left in the 488 MB of addons I have, so I thought I'd mentiion it.

**Comment by biggianteye** [comment]
Should be fixed by https://github.com/SpareSimian/FixPlaySound/pull/3

**Comment by SpareSimian** [comment]
Closed and fixed by your pull request #3. Thanks!
